### ISSUE TITLE
Inquiry on Analyzing Bronze and Silver Standards in baker Package

### ISSUE THREAD

**Issue by potatolover222** [zhenkewu/baker#24]
Hi, Mr. Zhenke Wu,

I hope this message finds you well. I am currently utilizing the baker package for my research and have a specific question regarding the simultaneous analysis of bronze and silver standards.

My understanding is that the Y vector in the baker package specifies the grouping information for the bronze standard, with the assumption that the silver standard includes only cases without a control group by default.

Could you please clarify if it is mandatory for the same set of cases to undergo both bronze and silver standard tests? Specifically, does baker require that all cases included in the analysis have results from both bronze and silver standard tests, as opposed to some cases having only bronze standard results and others having only silver standard results?

Understanding this requirement is crucial for the accurate interpretation of my data and the correct application of the baker package in my analysis.

Thank you for your time and assistance.

**Comment by zhenkewu** [comment]
Hi @potatolover222 ,

Thanks for the questions.

`Could you please clarify if it is mandatory for the same set of cases to undergo both bronze and silver standard tests?`

No. You may specify `NA` for a subset of subjects (cases in your situation) if they have either silver or bronze missing. I understand this is only necessary if you DO have a subset of subjects that have both silver and bronze standard data. In the likelihood, there is an option of specifying `use_measurements`; see [here](https://github.com/zhenkewu/baker/blob/master/R/nplcm.R/#L46). 

`Specifically, does baker require that all cases included in the analysis have results from both bronze and silver standard tests, as opposed to some cases having only bronze standard results and others having only silver standard results?`

No. As above.

**Comment by potatolover222** [comment]
Hi Mr. Zhenke Wu,
   
Your prompt and detailed response was immensely helpful. I truly appreciate your expertise and the time you took to help me.

Thank you once again for your support.
